import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import Header from "./components/Header";
import AuthProvider from "./context/AuthContext";
import "./globals.css";
import Footer from "./components/Footer";



export const metadata: Metadata = {
  title: "Adopta",
  description: "Generated by create next app",
};

//Font
const lexend = Lexend(
  {
    variable: '--font-lexend',
    subsets: ["latin"]
  }
)


export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  //Get the current use loged in

  const currentYear = new Date().getFullYear()


  return (
    <html lang="en">
      <body className={`${lexend.variable}`}>
        <AuthProvider>
          <div className='min-h-screen flex flex-col'>
            <Header />
            <main className="flex-1">
              {children}
            </main>
            <Footer currentYear={currentYear} />
          </div>
        </AuthProvider>
      </body>
    </html >
  );
}
