import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";



export const metadata: Metadata = {
  title: "Adopta",
  description: "Generated by create next app",
};

//Font
const lexend = Lexend(
  {
    variable: '--font-lexend',
    subsets: ["latin"]
  }
)

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  //Get the current use loged in

  return (
    <html lang="en">
      <body className={`${lexend.variable}`}>
        <div className='min-h-screen'>
          <Header />
          {children}
        </div>
      </body>
    </html >
  );
}
